<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ExpenseAccountCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required',
            'income_account_id'=>'required'
        ];
    }

    public function attributes()
    {
        return [
            'name'=>'Nombre',
            'income_account_id'=>'Cuenta de Ingreso'
        ];// TODO: Change the autogenerated stub
    }

    public function response(array $errors)
    {
        return response()->json($errors,422);
    }
}
