<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class InternalControlCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'number'=>'required|numeric',
            'balance'=>'required',
            'number_of_envelopes'=>'required|numeric',
            'saturday'=>'required|date|unique:internal_controls,saturday'
        ];
    }

    public function attributes()
    {
        return [
            'number'=>'Numero Control Interno',
            'balance'=>'Total',
            'number_of_envelopes'=>'Cantidad de Sobres',
            'saturday'=>'Sabado'
        ];// TODO: Change the autogenerated stub
    }

    public function response(array $errors)
    {
        return response()->json($errors,422);
    }
}
